---
repo-name: peripherals-postgres
categories:
- Database
- Storage
display-name: PostgreSQL
manufacture: 
product: PostgreSQL
description: A free and open-source relational database management system (RDBMS) emphasizing extensibility and technical standards compliance.
